"use strict";

//~> Logo de la página /
export const logo = "../imagenes/site_images/logos-qr/Logo.png";

//~> Base de datos de las publicaciones en Codepen /
export const articlesCodePenDB =
[
    {
      codePenLink:"https://codepen.io/rubenmosqueda",
      image:"../imagenes/site_images/miniatures/codepen_my_codepen_space.jpg",
      title:"My CodePen Space",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/jOpwEBZ",
      image:"../imagenes/site_images/miniatures/codepen_layout_responsive.jpg",
      title:"Layout Responsive",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/QWBpzzY",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_responsive_with_javascript.jpg",
      title:"Accordion List Responsive with JavaScript",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/jOpMJMp",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_with_transition_css.jpg",
      title:"Accordion List With Transition CSS",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/oNMzaWO",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_css.JPG",
      title:"Accordion List CSS",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/RwJOVGp",
      image:"../imagenes/site_images/miniatures/codepen_e_book_card.JPG",
      title:"e-Book Responsive Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/ZERZpvR",
      image:"../imagenes/site_images/miniatures/codepen_fake_window_card.JPG",
      title:"Window Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/NWzJEXq",
      image:"../imagenes/site_images/miniatures/codepen_behance_card.JPG",
      title:"Behance Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/WNymygW",
      image:"../imagenes/site_images/miniatures/codepen_card.JPG",
      title:"Codepen Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/WNyopYK",
      image:"../imagenes/site_images/miniatures/codepen_landing_page_exercise.JPG",
      title:"Personal Landing Page Exercise",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/zYWPoVQ",
      image:"../imagenes/site_images/miniatures/codepen_css_sprite_animation.JPG",
      title:"CSS Sprite Animation",
      author:"Rubén Mosqueda"
    }
]

//~> Base de datos de Diseños /
export const articlesDesingDB =
[  
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_board_for_food_menu_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_board_for_food_menu.jpg",
      title:"Concept Food Menu Board",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_book_miniatures.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_book.jpg",
      title:"Concept Card Book",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano.jpg",
      title:"Concept Cofee Card Artesano",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_inspiration_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_inspiration.jpg",
      title:"Cafeteria Artesano",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari.jpg",
      title:"Concept Cofee Card Caligari",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_inspiration_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_inspiration.jpg",
      title:"Cafeteria Caligari",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_food_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_food.jpg",
      title:"Concpet Food Card",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_fox_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_fox.jpg",
      title:"Concept Interface Fox",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_control_panel.png",
      title:"Concept Control Panel Fox",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/desing_tommy_slide_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/desing_tommy_slide.jpg",
      title:"Cafeteria Tommy Slide",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madres_dc_chips_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madres_dc_chips.jpg",
      title:"Tarjeta Madre DC Chips",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman.jpg",
      title:"Cafe Talisman",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_2_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_2.jpg",
      title:"Cafe Talisman",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madre_asus_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madre_asus.jpg",
      title:"Tarjeta Madre Asus Maximus Hero IX",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_comisiones_art_miniarure.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_comisiones_art.jpg",
      title:"Streamer Comissions",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_kpt_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_kpt.jpg",
      title:"Presentacion Kits para Todos",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_pusheen_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_pusheen.jpg",
      title:"Paneles Pusheen",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_hoja_vida_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_hoja_vida.png",
      title:"Hoja de Vida",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_la_gorda_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_la_gorda.jpg",
      title:"Presentation Desing La Gorda",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/web_concept_la_gorda_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/web_concept_la_gorda.png",
      title:"Web Concept La Gorda",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/web_concept_tacos_al_pastor_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/web_concept_tacos_al_pastor.jpg",
      title:"Web Concept Tacos al Pastor",
      author:"Rubén Mosqueda"
    },
]

//~> Base de datos de Imagenes de Recursos /
export const resourcesDB = 
[  
    {
      link:"../imagenes/public_resources/Emotes/Emote.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_1.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_10.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_11.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_12.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_13.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_14.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_3.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_4.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_404_FoxTales.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_404_FoxTales_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_5.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_6.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_7.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_8.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_9.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox_3.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Nadeshiko.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Nadeshiko_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Pusheen.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_404_FoxTales.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Fox.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Fox_2.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Zorro_404.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Rin.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Rin_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_adobe_xd.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_adobe_xd_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_aliexpress_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_amazon_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_arrow.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_atom.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_atom_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_background_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance_hex000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_bell_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_bell_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_blogger_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_blogger_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_book.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_camera.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_canva.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_car.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_chef.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cine_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_clock.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_codepen.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_coffe_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_coffe_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_computer.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_copywriter.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_css.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_css_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cup.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_didi.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_download.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_epic.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_excel.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_facebook.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_facebook_new.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_favorite.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_figma.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_figma_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_flac.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_forks.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_dark2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_coffee.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_histories_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_histories_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_home_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_home_ligth.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_0093b3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_336b83.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_563a2f.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_827565.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_movies_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_movies_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_series_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_series_ligth.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_settings_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_settings_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_share.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_fox_minimal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_galeria_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_gdrive.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github_portfolio_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_212121.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_glass.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_gmail.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_a_hex_272729.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_a_hex_d76f38.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_heart.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_html.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_html_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_azul.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_azul_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_blanca.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_cafe.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_negra.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_rosa.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_images_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_javascript.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_key.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kick_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_cpu.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_disipador.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_motherboard.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_pc.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_ram.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_ssd.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_video.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_clasicos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_comal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_mole.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_mostrador.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_nuevo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_picosidad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_tardamos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_tipicos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda__barrio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_leaf_streamer.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_leaf_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_leagueoflegends.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lectura_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_linkedin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_linkedin_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_2_hex_272729.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_portfolio_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_tacospastor_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_man.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_moon_star_streamer_1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_moon_star_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_motherboard.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_movie.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_musica_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_netflix.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_notepad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_notion.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_otaku.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pc.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pc_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_phone.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_phone_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_photoshop.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_photoshop_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pinterest.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_plus.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_prime_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_processor.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rappi.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_reddit.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_responsive.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rmb_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rmb_logo_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rss.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_running_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_seo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_settings.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_settings_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_share_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_share_hex_d6d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_skype.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_star.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_stars_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_stars_streamer_3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_star_streamer_1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_steam.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tablet.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_car.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_facebook.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_pin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_tacospastor_telefono.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_television.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_television_minimal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tumblr.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_lagorda_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_lagorda_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_x.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitter_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_uber_eats.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_uber_eats_hex_14a5ce.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ui_ux.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_videojuegos_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_visual_studio_code_blue.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_visual_studio_code_purple.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_web.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_word.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_youtube.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_wordpress.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Overlays.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Agradecimientos.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Alertas.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Clean.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Comandos.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Discord.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Donaciones.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel F.A.Q.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Instagram.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Juegos Completados.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Pc Specs.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Priscy Verso.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Reglas.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Subscripcion.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Top Donadores.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Wish List.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/38303557-fotografía-del-artista-vino-tinto-imprimado-lienzo-pato-algodón-gruesa-textura-grunge-.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/40928576-textura-verde-oscuro-fondo-de-cuero-patrón-de-la-tela.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/background.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/codepenHeader.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/diseño_background.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Fabric Merchants Ponte de Roma Solid Wine.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Fabricut Topaz Nile Fabric - Fabricut Topaz Nile Fabric _ Topaz _ Nile.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellitas_1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellitas_2.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellitas_3.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellitas_4.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellita_Azul_2.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Huellita_Azul_4.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/instagramHeader.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Mantel_rojo.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Mantel_veige.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Mantel_verde.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/PanalBackground.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/PanalBackgroundBlack.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/PanalBackgroundWhite.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/T75511.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura2.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_2.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_3.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_4.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_5.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_6.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_7.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_8.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_Azulejo_9.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_cuadro_1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_flores_1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_naranja_1.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_naranja_2.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_naranja_3.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_roja_1.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_veige_1.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_verde_1 (2).jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_verde_1.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/Textura_verde_2.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture_1.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture_2.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture_3.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture_4.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/texture_5.png",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Texturas/thumb-0001-1920x1080.jpg",
      type:"Texturas",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_bird_flying.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_3.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_4.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_5.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_fox_sheet.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_porfolio_invoke.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_porfolio_sheet.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_porfolio_walk.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_porfolio_work_left.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_porfolio_work_right.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_air_combo_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_air_combo_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_air_combo_3.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_dash.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_die.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_groundcombo_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_groundcombo_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_groundcombo_3.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_idle.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_jumpandfall.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_run.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_shootgun_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_shootgun_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_shoot_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_shoot_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_way_1.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy_way_2.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_shotguy__ungingstab.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/sprite_walkingdemo-hank-2-sheet.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Sprites/TakeHit.png",
      type:"Sprites",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/cafe artesano2.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Cafe_caligari.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Celular.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Gemini_Generated_Image_1qon801qon801qon-Photoroom.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Gemini_Generated_Image_6sj8d56sj8d56sj8-Photoroom.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Gemini_Generated_Image_em5g7yem5g7yem5g_processed.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Gemini_Generated_Image_nhq8wlnhq8wlnhq8_processed.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Gemini_Generated_Image_xhxd2axhxd2axhxd_processed.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/GranosDeCafe.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Home.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/IA_Pet.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Jericalla_1.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Laptop3.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Limon.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Limon_1.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Limon_2.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Monitor.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Naranja.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/PaletaDeColores.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Platillo de Prueba.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-cafe-americano.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-chilaquiles-divorciados.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-hotcakes-frutales.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-huevo-ranchero.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-licuado-tropical.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/platillo-molletes-dulces-salados.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/plato.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Tablet (2).png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_1.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_2.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_3.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_4.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_5.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Taco_6.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Talisman_Cafeteria_Clean.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/thumb-0030-1920x1138.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/pngs/Trompo_Pastor_4.png",
      type:"recursos-pngs",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_001.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_002.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_003.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_004.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_005.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_006.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_007.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_008.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_009.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_010.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_011.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_012.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_013.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_014.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_015.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_016.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_017.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_018.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_019.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_020.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_021.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_022.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_023.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_024.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_025.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_026.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_027.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_028.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_029.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_030.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_031.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_032.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_033.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_034.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_035.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_036.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_037.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_038.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_039.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_040.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_041.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_042.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_043.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_044.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_045.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_046.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_047.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_048.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_049.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_050.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_051.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_052.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_053.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_054.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_055.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_056.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_057.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_058.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_059.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_060.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_061.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_062.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_063.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_064.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_065.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_066.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_067.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_068.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_069.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_070.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_071.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_072.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_073.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_074.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_075.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_076.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_077.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_078.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_079.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_080.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_081.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_082.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_083.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_084.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_085.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_086.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_087.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_088.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_089.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_090.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_091.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_092.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_093.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_094.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_095.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_096.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_097.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_098.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_099.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_100.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_101.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_102.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_103.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_104.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_105.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_106.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_107.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_108.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_109.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_110.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_111.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_112.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_113.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_114.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_115.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_116.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_117.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_118.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_119.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_120.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_121.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_122.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_123.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_124.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_125.webp",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_126.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_127.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_128.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_129.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_130.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_131.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_132.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_133.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_134.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_135.png",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_136.jpeg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_137.jpeg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_138.jpeg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_139.jpeg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_140.jpeg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_141.jpg",
      type:"recursos-stok",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Recursos/stok/stok_image_142.jpg",
      type:"recursos-stok",
      project:"none",
    }
]
