"use strict";

//~> Logo de la página /
export const logo = "../imagenes/site_images/logos-qr/Logo.png";

//~> Base de datos de las publicaciones en Codepen /
export const articlesCodePenDB =
[
    {
      codePenLink:"https://codepen.io/rubenmosqueda",
      image:"../imagenes/site_images/miniatures/codepen_my_codepen_space.jpg",
      title:"My CodePen Space",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/jOpwEBZ",
      image:"../imagenes/site_images/miniatures/codepen_layout_responsive.jpg",
      title:"Layout Responsive",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/QWBpzzY",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_responsive_with_javascript.jpg",
      title:"Accordion List Responsive with JavaScript",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/jOpMJMp",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_with_transition_css.jpg",
      title:"Accordion List With Transition CSS",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/oNMzaWO",
      image:"../imagenes/site_images/miniatures/codepen_accordion_list_css.JPG",
      title:"Accordion List CSS",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/RwJOVGp",
      image:"../imagenes/site_images/miniatures/codepen_e_book_card.JPG",
      title:"e-Book Responsive Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/ZERZpvR",
      image:"../imagenes/site_images/miniatures/codepen_fake_window_card.JPG",
      title:"Window Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/NWzJEXq",
      image:"../imagenes/site_images/miniatures/codepen_behance_card.JPG",
      title:"Behance Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/WNymygW",
      image:"../imagenes/site_images/miniatures/codepen_card.JPG",
      title:"Codepen Card",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/WNyopYK",
      image:"../imagenes/site_images/miniatures/codepen_landing_page_exercise.JPG",
      title:"Personal Landing Page Exercise",
      author:"Rubén Mosqueda"
    },
    {
      codePenLink:"https://codepen.io/rubenmosqueda/pen/zYWPoVQ",
      image:"../imagenes/site_images/miniatures/codepen_css_sprite_animation.JPG",
      title:"CSS Sprite Animation",
      author:"Rubén Mosqueda"
    }
]

//~> Base de datos de Diseños /
export const articlesDesingDB =
[  
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_board_for_food_menu_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_board_for_food_menu.jpg",
      title:"Concept Food Menu Board",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_book_miniatures.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_book.jpg",
      title:"Concept Card Book",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano.jpg",
      title:"Concept Cofee Card Artesano",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_inspiration_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_artesano_inspiration.jpg",
      title:"Cafeteria Artesano",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari.jpg",
      title:"Concept Cofee Card Caligari",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_inspiration_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_coffee_caligari_inspiration.jpg",
      title:"Cafeteria Caligari",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_card_food_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_card_food.jpg",
      title:"Concpet Food Card",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_fox_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_fox.jpg",
      title:"Concept Interface Fox",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/concept_control_panel_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/concept_control_panel.png",
      title:"Concept Control Panel Fox",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/desing_tommy_slide_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/desing_tommy_slide.jpg",
      title:"Cafeteria Tommy Slide",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madres_dc_chips_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madres_dc_chips.jpg",
      title:"Tarjeta Madre DC Chips",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman.jpg",
      title:"Cafe Talisman",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_2_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/design_cofee_talisman_2.jpg",
      title:"Cafe Talisman",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madre_asus_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/proyecto_tarjeta_madre_asus.jpg",
      title:"Tarjeta Madre Asus Maximus Hero IX",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_comisiones_art_miniarure.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_comisiones_art.jpg",
      title:"Streamer Comissions",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_kpt_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_kpt.jpg",
      title:"Presentacion Kits para Todos",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_pusheen_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_pusheen.jpg",
      title:"Paneles Pusheen",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_hoja_vida_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_hoja_vida.png",
      title:"Hoja de Vida",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/presentacion_la_gorda_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/presentacion_la_gorda.jpg",
      title:"Presentation Desing La Gorda",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/web_concept_la_gorda_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/web_concept_la_gorda.png",
      title:"Web Concept La Gorda",
      author:"Rubén Mosqueda"
    },
    {
      miniature:"../imagenes/public_resources/Mis_Disenos/web_concept_tacos_al_pastor_miniature.jpg",
      image:"../imagenes/public_resources/Mis_Disenos/web_concept_tacos_al_pastor.jpg",
      title:"Web Concept Tacos al Pastor",
      author:"Rubén Mosqueda"
    },
]

//~> Base de datos de Imagenes /
export const resourcesDB =
[  
    {
      link:"../imagenes/public_resources/Emotes/Emote.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_1.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_10.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_11.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_12.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_13.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_14.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_3.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_4.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_404_FoxTales.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_404_FoxTales_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_5.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_6.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_7.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_8.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_9.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Fox_3.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Nadeshiko.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Nadeshiko_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Pusheen.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_404_FoxTales.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Fox.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Fox_2.jpg",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Referencia_Zorro_404.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Rin.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Emotes/Emote_Rin_2.png",
      type:"emote",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icono_twiter_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_adobe_xd.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_adobe_xd_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_aliexpress_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_amazon_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_arrow.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_atom.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_atom_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_background_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance_hex000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_behance_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_bell_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_bell_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_blogger_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_blogger_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_book.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_camera.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cancel_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_canva.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_car.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_chef.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cine_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_clock.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_codepen.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_coffe_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_coffe_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_computer.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_copywriter.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_css.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_css_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_cup.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_didi.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_download.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_epic.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_excel.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_facebook.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_facebook_new.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_favorite.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_figma.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_figma_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_flac.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_forks.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_dark2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_biblioteca_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_coffee.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_histories_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_histories_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_home_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_home_ligth.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_0093b3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_336b83.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_563a2f.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_logo_hex_827565.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_movies_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_movies_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_series_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_series_ligth.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_settings_dark.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_settings_light.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_foxtales_share.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_fox_minimal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_galeria_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_gdrive.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_github_portfolio_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_212121.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_git_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_glass.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_gmail.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_a_hex_272729.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_a_hex_d76f38.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_heart.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_home_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_html.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_html_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_azul.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_azul_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_blanca.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_cafe.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_negra.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_huellita_rosa.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_images_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_instagram_new_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_javascript.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_key.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kick_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ko_fi_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_cpu.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_disipador.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_motherboard.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_pc.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_ram.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_ssd.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_kpt_video.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_clasicos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_comal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_mole.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_mostrador.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_nuevo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_picosidad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_tardamos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda_tipicos.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lagorda__barrio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_leaf_streamer.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_leaf_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_leagueoflegends.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_lectura_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_linkedin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_linkedin_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_2_hex_272729.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_hex_d5d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_portfolio_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_mail_tacospastor_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_man.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_moon_star_streamer_1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_moon_star_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_motherboard.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_movie.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_musica_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_netflix.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_notepad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_notion.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_otaku.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pc.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pc_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_phone.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_phone_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_photoshop.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_photoshop_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_pinterest.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_plus.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_prime_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_processor.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rappi.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_reddit.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_responsive.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rmb_logo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rmb_logo_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_rss.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_running_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_seo.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_settings.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_settings_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_share_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_share_hex_d6d9da.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_skype.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_star.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_stars_streamer_2.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_stars_streamer_3.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_star_streamer_1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_steam.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tablet.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_car.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_facebook.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tacospastor_pin.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_tacospastor_telefono.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_television.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_television_minimal.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tumblr.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_lagorda_hex_000000.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_lagorda_hex_d0c5ad.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_tweeter_x.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_92fd70.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_c684ff.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitch_streamer_hex_fbccd1.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_twitter_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_uber_eats.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_uber_eats_hex_14a5ce.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_ui_ux.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_videojuegos_portfolio.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_visual_studio_code_blue.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_visual_studio_code_purple.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/Icon_web.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_word.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_youtube.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Iconos/icon_wordpress.png",
      type:"icon",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Overlays.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Agradecimientos.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Alertas.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Clean.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Comandos.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Discord.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Donaciones.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel F.A.Q.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Instagram.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Juegos Completados.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Pc Specs.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Priscy Verso.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Reglas.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Subscripcion.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Top Donadores.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel Wish List.png",
      type:"Paneles",
      project:"none",
    },
    {
      link:"../imagenes/public_resources/Paneles/Panel.png",
      type:"Paneles",
      project:"none",
    }
]
